config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  resources :orders, only: [:index, :new, :create]
  resources :items, only: [:index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  namespace :admin do
    resources :users, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
  validates :total_quantity, presence: true
  has_many :orders, through: :ordered_lists
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :ordered_lists
  has_many :items, through: :ordered_lists
  accepts_nested_attributes_for :ordered_lists

  def update_total_quantity
    ActiveRecord::Base.transaction do
      self.ordered_lists.each do |line_item|
        item = Item.lock.find_by(id: line_item.item_id)
        item.total_quantity += line_item.quantity
        item.save!
      end
    end
  end
end

app/models/ordered_list.rb
class OrderedList < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
    @user=User.new
  end

  def create
    @user=User.new(user_params)
    if @user.save
      @user.update(admin: true)
      log_in @user
      redirect_to items_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :admin_required, only: [:index]

  def index
    @items = Item.all.order(:created_at)
  end

  private

  def admin_required
    redirect_to orders_path unless current_user.admin?
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.where(user_id: current_user.id).order(created_at: :desc)
  end

  def new
    @order = Order.new
    @order.ordered_lists.build
    @items = Item.all.order(:created_at)
  end

  def create
    @order = current_user.orders.build(order_params)
    @order.save
    @order.update_total_quantity
    # update_total_quantityメソッドは、注文された発注量を総量に反映するメソッドであり、Orderモデルに定義されています。
    redirect_to orders_path
  end

  private

  def order_params
    params.require(:order).permit(ordered_lists_attributes: [:item_id, :quantity])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      log_in(user)
      redirect_to items_path
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:show]
  skip_before_action :login_required, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to new_order_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to current_user unless current_user?(@user)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user.present?
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user?(user)
    user == current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/new.html.erb
<h1>Sign up</h1>

<%= form_with(model: [:admin, @user], local: true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit "Create my account" %>
  </div>
<% end %>

app/views/items/index.html.erb
<h1>受注一覧</h1>

<table border=1>
  <thead>
    <tr>
      <td>商品名</td><td>注文数</td>
    </tr>
  </thead>
  <tbody>
  <% @items.each do |item| %>
    <tr>
      <td><%= item.name %></td>
      <td><%= item.total_quantity %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SessionLogin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% if logged_in? %>
      <%= link_to "発注一覧", orders_path unless current_user.admin? %>
      <%= link_to "発注する", new_order_path unless current_user.admin? %>
      <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "アカウント登録", new_user_path %>
      <%= link_to "ログイン", new_session_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<h1>発注一覧</h1>

<% if !@orders.present? %>
  <p>注文した商品はありません。</p>
<% end %>

<% @orders.each do |order| %>
  <p>
    <strong>発注日時:</strong>
    <%= order.created_at.strftime("%m/%d %H:%M") %>
  </p>

  <table border=1>
    <thead>
      <tr>
        <td width=100px>商品名</td>
        <td>注文数</td>
      </tr>
    </thead>
    <tbody>
      <% order.ordered_lists.order(item_id: :asc).each do |ordered_list| %>
      <% if ordered_list.quantity != 0 %>
        <tr>
          <td><%= Item.find_by(id: ordered_list.item_id).name %></td>
          <td><%= ordered_list.quantity %></td>
        </tr>
      <% end %>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/orders/new.html.erb
<h1>発注登録</h1>

<%= form_with(model: @order, local: true) do |form| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>
      <ul>
        <% @order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table border=1>
    <thead>
      <tr>
        <td>商品名</td>
        <td>注文数</td>
      </tr>
    </thead>
    <tbody>
    <% @items.each do |item| %>
      <%= form.fields_for(:ordered_lists) do |f| %>
        <tr>
          <td><%= item.name %></td>
          <td><%= f.number_field :quantity, min: 0, max: 10 %></td>
        </tr>
        <%= f.hidden_field :item_id, value:item.id %>
      <% end %>
    <% end %>
    </tbody>
  </table>
  <%= form.submit '注文する' %>
<% end %>

app/views/users/new.html.erb
<h1>サインイン</h1>

<%= form_with(model: @user, local: true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :名前 %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :メールアドレス %>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :パスワード %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :パスワード（確認） %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit "登録" %>
  </div>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1>アカウント詳細</h1>

<p>
  <strong>名前:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>メールアドレス:</strong>
  <%= @user.email %>
</p>